In [1]:
import jax 
import jax.numpy as jnp

In [16]:
key = jax.random.PRNGKey(0)

key

Array([0, 0], dtype=uint32)

In [17]:
key, subk = jax.random.split(key, 2)

key, subk

(Array([4146024105,  967050713], dtype=uint32),
 Array([2718843009, 1272950319], dtype=uint32))